import { SellerProfile, Product, Order, Review, ChatMessage } from '@/types';

export const MOCK_SELLERS: SellerProfile[] = [
  {
    id: 'seller-1',
    userId: 'user-seller-1',
    storeName: "Student Bites",
    storeSlug: 'student-bites',
    bio: 'Affordable homemade meals, fresh Gatsbys & burgers delivered right to your lecture hall or residence.',
    logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    campusId: 'cput-bellville',
    campusName: 'CPUT Bellville Campus',
    isOpen: true,
    ratingAvg: 4.8,
    ratingCount: 142,
    contactNumber: '+27721234567',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'seller-2',
    userId: 'user-seller-2',
    storeName: "Lebo's Snack Stop",
    storeSlug: 'lebos-snack-stop',
    bio: 'Your quick break fix! Local South African crisps, instant noodles, Simba, and NikNaks.',
    logoUrl: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=800&q=80',
    campusId: 'cput-district-six',
    campusName: 'CPUT District Six Campus',
    isOpen: true,
    ratingAvg: 4.9,
    ratingCount: 98,
    contactNumber: '+27839876543',
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: 'seller-3',
    userId: 'user-seller-3',
    storeName: "Nadia's Nibbles",
    storeSlug: 'nadias-nibbles',
    bio: 'Cape Town style Samoosas, mini Vetkoek, toasted sandwiches and sweet delights made fresh daily.',
    logoUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    campusId: 'uct-upper',
    campusName: 'UCT Upper Campus',
    isOpen: true,
    ratingAvg: 4.7,
    ratingCount: 215,
    contactNumber: '+27614567890',
    createdAt: '2025-01-05T09:00:00Z',
  },
  {
    id: 'seller-4',
    userId: 'user-seller-4',
    storeName: "The Study Break Bar",
    storeSlug: 'the-study-break-bar',
    bio: 'Ice cold Steri Stumpie, energy drinks, cold bottled water, and iced coffees for study sessions.',
    logoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=800&q=80',
    campusId: 'uwc-main',
    campusName: 'UWC Main Campus',
    isOpen: true,
    ratingAvg: 4.8,
    ratingCount: 64,
    contactNumber: '+27741122334',
    createdAt: '2025-01-20T14:30:00Z',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'seller-1',
    sellerName: 'Student Bites',
    sellerSlug: 'student-bites',
    sellerRating: 4.8,
    categoryId: 'cat-meals',
    categoryName: 'Meals',
    name: 'Full Chicken Gatsby with Chips',
    slug: 'full-chicken-gatsby',
    description: 'Freshly toasted footlong Gatsby packed with spiced chicken strip, hot slap chips, salad & spicy sauce.',
    priceCents: 4500, // R45.00
    imageUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['cput-bellville', 'cput-district-six', 'uct-upper', 'uwc-main', 'su-main'],
    tag: 'Popular',
    eta: '12-15 min',
    createdAt: '2025-01-10T10:30:00Z',
  },
  {
    id: 'prod-2',
    sellerId: 'seller-1',
    sellerName: 'Student Bites',
    sellerSlug: 'student-bites',
    sellerRating: 4.8,
    categoryId: 'cat-fast-food',
    categoryName: 'Fast Food',
    name: 'Student Double Beef Burger & Slap Chips',
    slug: 'double-beef-burger',
    description: 'Juicy double grilled beef patty with cheese, caramelized onions, sauce and a generous portion of chips.',
    priceCents: 3500, // R35.00
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['cput-bellville', 'uct-upper', 'su-main'],
    tag: 'Best Value',
    eta: '10-12 min',
    createdAt: '2025-01-10T11:00:00Z',
  },
  {
    id: 'prod-3',
    sellerId: 'seller-3',
    sellerName: "Nadia's Nibbles",
    sellerSlug: 'nadias-nibbles',
    sellerRating: 4.7,
    categoryId: 'cat-lunch',
    categoryName: 'Lunch',
    name: 'Toasted Chicken Mayo Sandwich',
    slug: 'toasted-chicken-mayo',
    description: 'Crispy toasted golden white or brown bread with seasoned shredded chicken breast and creamy mayo.',
    priceCents: 2800, // R28.00
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['uct-upper', 'uct-middle', 'su-main'],
    tag: 'Fresh',
    eta: '8-10 min',
    createdAt: '2025-01-12T09:15:00Z',
  },
  {
    id: 'prod-4',
    sellerId: 'seller-3',
    sellerName: "Nadia's Nibbles",
    sellerSlug: 'nadias-nibbles',
    sellerRating: 4.7,
    categoryId: 'cat-snacks',
    categoryName: 'Snacks',
    name: 'Cape Samoosas (Pack of 4 - Mince & Cheese)',
    slug: 'samoosas-4-pack',
    description: 'Golden crispy pastry triangles filled with spiced beef mince or melted cheese & sweetcorn.',
    priceCents: 2000, // R20.00
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['uct-upper', 'cput-bellville', 'uwc-main'],
    tag: 'Hot Snack',
    eta: '5-8 min',
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'prod-5',
    sellerId: 'seller-2',
    sellerName: "Lebo's Snack Stop",
    sellerSlug: 'lebos-snack-stop',
    sellerRating: 4.9,
    categoryId: 'cat-snacks',
    categoryName: 'Snacks',
    name: 'Chakalaka Simba Chips (120g Big Bag)',
    slug: 'simba-chakalaka',
    description: 'The classic South African potato chip with authentic spicy Chakalaka flavor.',
    priceCents: 1500, // R15.00
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['cput-district-six', 'cput-bellville', 'uwc-main'],
    tag: 'Popular',
    eta: '5-7 min',
    createdAt: '2025-01-15T12:30:00Z',
  },
  {
    id: 'prod-6',
    sellerId: 'seller-2',
    sellerName: "Lebo's Snack Stop",
    sellerSlug: 'lebos-snack-stop',
    sellerRating: 4.9,
    categoryId: 'cat-noodles',
    categoryName: 'Noodles',
    name: 'Cooked Hot 2-Minute Noodles (Spicy Beef)',
    slug: 'cooked-instant-noodles',
    description: 'Served piping hot in a takeaway bowl with extra chilli flakes and melted cheese topping.',
    priceCents: 2200, // R22.00
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['cput-district-six', 'cput-bellville', 'uct-upper'],
    tag: 'Warm Meal',
    eta: '8-10 min',
    createdAt: '2025-01-15T13:00:00Z',
  },
  {
    id: 'prod-7',
    sellerId: 'seller-4',
    sellerName: "The Study Break Bar",
    sellerSlug: 'the-study-break-bar',
    sellerRating: 4.8,
    categoryId: 'cat-drinks',
    categoryName: 'Drinks',
    name: 'Steri Stumpie Flavoured Milk (350ml Ice Cold)',
    slug: 'steri-stumpie',
    description: 'Chilled iconic South African flavoured milk drink. Available in Chocolate, Strawberry, or Coffee.',
    priceCents: 1800, // R18.00
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['uwc-main', 'cput-bellville', 'uct-upper', 'su-main'],
    tag: 'Ice Cold',
    eta: '5 min',
    createdAt: '2025-01-20T14:45:00Z',
  },
  {
    id: 'prod-8',
    sellerId: 'seller-4',
    sellerName: "The Study Break Bar",
    sellerSlug: 'the-study-break-bar',
    sellerRating: 4.8,
    categoryId: 'cat-drinks',
    categoryName: 'Drinks',
    name: 'Monster Energy Drink (500ml Original / Sugar Free)',
    slug: 'monster-energy',
    description: 'Maximum energy booster to power you through late night study sessions and exam preparation.',
    priceCents: 2400, // R24.00
    imageUrl: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    campusIds: ['uwc-main', 'uct-upper', 'cput-bellville'],
    tag: 'Study Fuel',
    eta: '5 min',
    createdAt: '2025-01-20T15:00:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'CC-8901',
    buyerId: 'user-buyer-1',
    buyerName: 'Sipho Zulu',
    buyerPhone: '+27821112233',
    sellerId: 'seller-1',
    sellerName: 'Student Bites',
    campusId: 'cput-bellville',
    campusName: 'CPUT Bellville Campus',
    deliveryLocationId: 'loc-1',
    deliveryLocationName: 'Bellville Library Entrance',
    customLocationInstructions: 'I am wearing a yellow hoodie standing near the glass doors.',
    status: 'delivering',
    items: [
      {
        id: 'oi-1',
        productId: 'prod-1',
        productName: 'Full Chicken Gatsby with Chips',
        unitPriceCents: 4500,
        quantity: 1,
        totalPriceCents: 4500,
      },
      {
        id: 'oi-2',
        productId: 'prod-7',
        productName: 'Steri Stumpie Flavoured Milk',
        unitPriceCents: 1800,
        quantity: 1,
        totalPriceCents: 1800,
      },
    ],
    subtotalCents: 6300, // R63.00
    deliveryFeeCents: 200, // R2.00
    totalCents: 6500, // R65.00
    platformFeeCents: 50, // R0.50
    sellerNetEarningsCents: 6450, // R64.50
    paymentStatus: 'paid',
    paymentMethod: 'Instant EFT (Mock)',
    createdAt: '2025-02-28T12:15:00Z',
    updatedAt: '2025-02-28T12:30:00Z',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    orderId: 'ord-990',
    buyerId: 'user-buyer-2',
    buyerName: 'Anelisa M.',
    sellerId: 'seller-1',
    rating: 5,
    comment: 'Gatsby was piping hot and delivered directly to my seat in the library! Legendary service.',
    createdAt: '2025-02-27T14:10:00Z',
  },
  {
    id: 'rev-2',
    orderId: 'ord-985',
    buyerId: 'user-buyer-3',
    buyerName: 'Keagan P.',
    sellerId: 'seller-3',
    rating: 5,
    comment: 'Best Samoosas on Upper Campus. Fast delivery and super polite seller!',
    createdAt: '2025-02-26T11:45:00Z',
  },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    orderId: 'ord-1001',
    senderId: 'user-seller-1',
    senderName: 'Student Bites',
    senderRole: 'seller',
    receiverId: 'user-buyer-1',
    content: "Hi Sipho! I've packed your order. On my way to the Bellville Library entrance now.",
    isRead: true,
    createdAt: '2025-02-28T12:28:00Z',
  },
  {
    id: 'msg-2',
    orderId: 'ord-1001',
    senderId: 'user-buyer-1',
    senderName: 'Sipho Zulu',
    senderRole: 'buyer',
    receiverId: 'user-seller-1',
    content: "Awesome, thanks! I am standing right next to the main security desk.",
    isRead: true,
    createdAt: '2025-02-28T12:29:10Z',
  },
];
